services:
  nginx:
    image: nginx
    ports:
      - "5080:80"
    volumes:
      - ./config:/etc/nginx:ro
      - ./hugo-site/public:/usr/share/nginx/html/hugo-site:ro
      - ./public:/usr/share/nginx/html/public:ro
      - ./hidden:/usr/share/nginx/html/hidden:ro
